// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _06_NexaWorks_BackEnd.Data;

#nullable disable

namespace _06_NexaWorks_BackEnd.Migrations
{
    [DbContext(typeof(NexaWorksContext))]
    partial class NexaWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.OS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OS");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.Statut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomStatut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("DescriptionTexte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOS")
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdStatut")
                        .HasColumnType("int");

                    b.Property<int>("IdVersionProduit")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<string>("ResolutionTexte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdOS");

                    b.HasIndex("IdProduit");

                    b.HasIndex("IdStatut");

                    b.HasIndex("IdVersionProduit");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.VersionProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<string>("NomVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduit");

                    b.ToTable("VersionProduit");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.VersionProduitOS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOS")
                        .HasColumnType("int");

                    b.Property<int>("IdVersionProduit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOS");

                    b.HasIndex("IdVersionProduit");

                    b.ToTable("VersionProduitOS");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.Ticket", b =>
                {
                    b.HasOne("_06_NexaWorks_BackEnd.Models.OS", "OS")
                        .WithMany()
                        .HasForeignKey("IdOS")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_06_NexaWorks_BackEnd.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_06_NexaWorks_BackEnd.Models.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_06_NexaWorks_BackEnd.Models.VersionProduit", "VersionProduit")
                        .WithMany()
                        .HasForeignKey("IdVersionProduit")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("Produit");

                    b.Navigation("Statut");

                    b.Navigation("VersionProduit");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.VersionProduit", b =>
                {
                    b.HasOne("_06_NexaWorks_BackEnd.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("_06_NexaWorks_BackEnd.Models.VersionProduitOS", b =>
                {
                    b.HasOne("_06_NexaWorks_BackEnd.Models.OS", "OS")
                        .WithMany()
                        .HasForeignKey("IdOS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_06_NexaWorks_BackEnd.Models.VersionProduit", "VersionProduit")
                        .WithMany()
                        .HasForeignKey("IdVersionProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("VersionProduit");
                });
#pragma warning restore 612, 618
        }
    }
}
